""" Start of script """
# Block list
# View the blocks in the game and their ID
# There is going to be over 10000 blocks when ready
''' Dirt ''' # Category 1
block_dirtID = int(1)
block_coarseDirtID = int(2)
block_podzolID = int(3)
block_myceliumID = int(4)
block_grassPathID = int(5)
''' Stone ''' # Category 2
block_caveStoneID = float(1.1)
block_cobbleStoneID = float(1.2)
block_mossyCobbleStoneID = float(1.3)
block_smoothStoneID = float(1.4)
block_obsidianID = float(1.5)
block_bedrockID = float(1.6)
''' Slabs ''' # Category 3
block_dirtSlabID = float(2.1)
block_coarseDirtSlabID = float(2.2)
block_podzolSlabID = float(2.3)
block_myceliumSlabID = float(2.4)
block_grassPathSlabID = float(2.5)
block_caveStoneSlabID = float(2.6)
block_mossyCobbleStoneSlabID = float(2.7)
block_smoothStoneSlabID = float(2.8)
block_obsidianSlabID = float(2.9)
block_bedrockSlabID = float(2.10)
''' Stairs ''' # Category 4
block_dirtStairsID = float(3.1)
block_coarseDirtStairsID = float(3.2)
block_podzolStairsID = floay(3.3)
''' Ores ''' # Category 5
block_coalOreID = float(4.1)
block_ironOreID = float(4.2)
block_goldOreID = float(4.3)
block_redstoneOreID = float(4.4)
block_emeraldOreID = float(4.5)
block_diamondOreID = float(4.6)
block_lapisLazuliOreID = float(4.7)
block_netherQuartzOreID = float(4.8)
block_bronzeOreID = float(4.100)
block_silverOreID = float(4.101)
block_rubyOreID = float(4.102)
''' Saplings ''' # Category 6
block_oakSaplingID = float(5.1)
block_darkOakTreeSaplingID = float(5.2)
block_acaciaTreeSaplingID = float(5.3)
block_birchTreeSaplingID = float(5.4)
block_spruceTreeSaplingID = float(5.5)
block_jungleTreeSaplingID = float(5.6)
block_cherryTreeSaplingID = float(5.7)
block_locustTreeSaplingID = float(5.8)
block_appleTreeSaplingID = float(5.9)
block_ashTreeSaplingID = float(5.10)
''' Beds ''' # Category 7
block_redBasicBedID = float(6.1)
block_blueBasicBedID = float(6.2)
block_greenBasicBedID = float(6.3)
block_cyanBasicBedID = float(6.4)
block_magentaBasicBedID = float(6.5)
block_whiteBasicBedID = float(6.6)
block_blackBasicBedID = float(6.7)
''' Wood ''' # Category 8
block_oakWoodPlankID = float(7.1)
block_darkOakWoodPlankID = float(7.2)
block_acaciaWoodPlankID = float(7.3)
block_birchWoodPlankID = float(7.4)
block_spruceWoodPlankID = float(7.5)
block_jungleWoodPlankID = float(7.6)
block_cherryWoodPlankID = float(7.7)
block_locustWoodPlankID = float(7.8)
block_appleWoodPlankID = float(7.9)
block_ashWoodPlankID = float(7.10)
block_oakWoodLogID = float(7.11)
block_darkOakWoodLogID = float(7.12)
block_acaciaWoodLogID = float(7.13)
block_birchWoodLogID = float(7.14)
block_spruceWoodLogID = float(7.15)
block_jungleWoodLogID = float(7.16)
block_cherryWoodLogID = float(7.17)
block_locustWoodLogID = float(7.18)
block_appleWoodLogID = float(7.19)
block_ashWoodLogID = float(7.20)
block_OldOakWoodLogID = float(7.21) # Old logs have rings in the middle. There can be a maximum of 8 rings. A ring automatically is created after 365 in-game days worth of time.
block_OldDarkOakWoodLogID = float(7.22)
block_OldAcaciaWoodLogID = float(7.23)
block_OldBirchWoodLogID = float(7.24)
block_OldSpruceWoodLogID = float(7.25)
block_OldJungleWoodLogID = float(7.26)
block_OldCherryWoodLogID = float(7.27)
block_OldLocustWoodLogID = float(7.28)
block_OldAppleWoodLogID = float(7.29)
block_OldAshWoodLogID = float(7.30)
''' Nether ''' # Category 9
block_magmaBlockID = float(8.1)
block_netherrackID = float(8.2)
block_soulSandID = float(8.3)
block_glowStoneID = float(8.4)
block_netherBrickBlockID = float(8.5)
block_redNetherBrickBlockID = float(8.6)
''' Glass ''' # Category 10
block_glassID = float(9.1)
block_glassPaneID = float(9.2)
block_whiteStainedGlassID = float(9.3)
block_whiteStainedGlassPaneID = float(9.4)
''' Appliances ''' # Category 11
block_furnaceID = float(10.1)
block_enderChestID = float(10.2)
block_OakWoodCraftingTableID = float(10.3)
block_ironCauldronID = float(10.4)
block_ironSpawnerCageID = float(10.5)
block_jukeBoxID = float(10.6)
block_oakWoodNoteblockID = float(10.7)
block_darkOakWoodNoteblockID = float(10.8)
block_acaciaWoodNoteblockID = float(10.9)
block_birchWoodNoteBlockID = float(10.10)
block_spruceWoodNoteBlockID = float(10.11)
block_jungleWoodNoteBlockID = float(10.12)
block_cherryWoodNoteBlockID = float(10.13)
block_locustWoodNoteBlockID = float(10.14)
block_appleWoodNoteBlockID = float(10.15)
block_ashWoodNoteBlockID = float(10.16)
block_DarkOakWoodCraftingTableID = float(10.17)
block_acaciaWoodCraftingTableID = float(10.18)
block_birchWoodCraftingTableID = float(10.19)
block_spruceWoodCraftingTableID = float(10.20)
block_jungleWoodCraftingTableID = float(10.21)
block_cherryWoodCraftingTableID = float(10.22)
block_locustWoodCraftingTableID = float(10.23)
block_appleWoodCraftingTableID = float(10.24)
block_ashWoodCraftingTableID = float(10.25)
''' Doors ''' # Category 12
block_ironDoorID = float(11.1)
block_steelDoorID = float(11.2)
block_oakWoodDoorID = float(11.3)
block_darkOakWoodDoorID = float(11.4)
block_acaciaWoodDoorID = float(11.5)
block_birchWoodDoorID = float(11.6)
block_spruceWoodDoorID = float(11.7)
block_jungleWoodDoorID = float(11.8)
block_cherryWoodDoorID = float(11.9)
block_locustWoodDoorID = float(11.10)
block_appleWoodDoorID = float(11.11)
block_ashWoodDoorID = float(11.12)
block_obsidianDoorID = float(11.13)
block_caveStoneDoorID = float(11.14)
block_goldDoorID = float(11.15)
block_diamondDoorID = float(11.16)
''' End ''' # Category 13
block_purpleEndCrystalID = float(12.1)
block_endStoneID = float(12.2)
block_enderDragonEggID = float(12.3)
block_endPortalID = float(12.4)
''' Clay ''' # Category 14
block_clayID = float(13.1)
block_whiteClayID = float(13.2)
''' Terracotta ''' # Category 15
block_whiteArrowTerracottaID = float(14.1)
''' Concrete ''' # Category 16
block_whiteConcretePowderID = float(15.1)
block_whiteConcreteID = float(15.2)
block_blackConcretePowderID = float(15.3)
block_blackConcreteID = float(15.4)
block_lightGreyConcretePowderID = float(15.5)
block_lightGreyConcreteID = float(15.6)
block_darkGreyConcretePowderID = float(15.7)
block_darkGreyConcreteID = float(15.8)
''' Carpet ''' # Category 17
block_whiteCarpetID = float(16.1)
''' Wool ''' # Category 18
block_whiteWoolID = float(17.1)
''' Redstone ''' # Category 19
block_redstoneBlockID = float(18.1)
block_redstoneTorchID = float(18.2)
block_goldenPressurePlateID = float(18.3)
block_CaveStoneLeverID = float(18.4)
block_cobbleStoneButtonID = float(18.5)
block_caveStoneButtonID = float(18.6)
block_pistonID = float(18.7)
block_stickyPistonID = float(18.8)
block_oakWoodPressurePlateID = float(18.9)
block_darkOakWoodPressurePlateID = float(18.10)
block_acaciaWoodPressurePlateID = float(18.11)
block_birchWoodPressurePlateID = float(18.12)
block_spruceWoodPressurePlateID = float(18.13)
block_jungleWoodPressurePlateID = float(18.14)
block_cherryWoodPressurePlateID = float(18.15)
block_locustWoodPressurePlateID = float(18.16)
block_appleWoodPressurePlateID = float(18.17)
block_ashWoodPressurePlateID = float(18.18)
block_pythonCommandBlockID = float(18.19)
block_NormalcommandBlockID = float(18.20)
''' On the wall ''' # Category 20
block_painting1ID = float(19.1)
block_torchID = float(19.2)
''' Frozen ''' # Category 21
block_snowBlockID = float(20.1)
block_snowID = float(20.2)
block_iceBlockID = float(20.3)
block_packedIceBlockID = float(20.4)
block_blueIceBlockID = float(20.5)
block_greenIceBlockID = float(20.6)
''' Fence-like ''' # Category 22
block_ironBarsID = float(21.1)
block_steelBarsID = float(21.2)
block_diamondBarsID = float(21.3)
block_oakWoodFenceID = float(21.4)
block_oakWoodWallID = float(21.5)
block_darkOakWoodFenceID = float(21.6)
block_darkOakWoodWallID = float(21.7)
block_acaciaWoodFenceID = float(21.8)
block_acaciaWoodWallID = float(21.9)
block_birchWoodFenceID = float(21.10)
block_spruceWoodFenceID = float(21.11)
block_jungleWoodFenceID = float(21.12)
block_cherryWoodFenceID = float(21.13)
block_locustWoodFenceID = float(21.14)
block_appleWoodFenceID = float(21.15)
block_ashWoodFenceID = float(21.16)
block_birchWoodWallID = float(21.17)
block_spruceWoodWallID = float(21.18)
block_jungleWoodWallID = float(21.19)
block_cherryWoodWallID = float(21.20)
block_locustWoodWallID = float(21.21)
block_appleWoodWallID = float(21.22)
block_ashWoodWallID = float(21.23)
''' Ocean Monument ''' # Category 23
block_prismarineBlockID = float(22.1)
block_prismarineBrickBlockID = float(22.2)
block_seaLanternBlockID = float(22.3)
''' Solid Ores ''' # Category 24
block_steelBlockID = float(23.1)
block_diamondBlockID = float(23.2)
block_ironBlockID = float(23.3)
block_goldBlockID = float(23.4)
block_emeraldBlockID = float(23.5)
block_BronzeBlockID = float(23.6)
block_silverBlockID = float(23.7)
block_rubyBlockID = float(23.8)
block_lapisLazuliBlockID = float(23.9)
block_coalBlockID = float(23.10)
''' Liquid ''' # Category 25
block_waterBlockID = float(24.1)
block_coldWaterBlockID = float(24.2)
block_soulWaterBlockID = float(24.3)
block_magmaWaterBlockID = float(24.4)
block_redLavaBlockID = float(24.5)
block_orangeLavaBlockID = float(24.6)
block_plainMilkBlockID = float(24.7)
block_chocolateMilkBlockID = float(24.8)
block_strawberryMilkBlockID = float(24.9)
block_greenAciBlockID = float(24.10)
block_urineBlockID = float(24.11)
block_oilBlockID = float(24.12)
block_tarBlockID = float(24.13)
block_gasolineBlockID = float(24.14)
block_petroleumBlockID = float(24.15)
block_steamingWaterBlockID = float(24.16)
''' Bones ''' # Category 26
block_ribcageBlockID = float(25.1)
block_skullBlockID = float(25.2)
''' Helpful ''' # Category 27
block_spongeID = float(26.1)
block_wetSpongeID = float(26.2)
''' Transportation ''' # Category 28
block_poweredRailID = float(27.1)
block_normalRailID = float(27.2)
block_activatorRailID = float(27.3)
block_wallRailID = float(27.4)
block_ceilingRailID = float(27.5)

''' Move '''
''' Tools ''' # Category 1
item_oakWoodBucketID = int(1)
item_darkOakWoodBucketID = int(2)
item_flintAndSteelID = int(3)
item_fireChargeID = int(4)
item_shearsID = int(5)
''' Potions and drinks ''' # Category 2
item_splashWaterBottleID = float(1.1)
item_bucketOfChocolateMilkID = float(1.2)
item_bucketOfStrawberryMilkID = float(1.3)
item_bottleOfChocolateMilkID = float(1.4)
item_bottkeOfStrawberryMilkID = float(1.5)
item_waterBottleID = float(1.6)
item_milkBucketID = float(1.7)
item_splashMilkBottleID = float(1.8)
''' Food and ingredients ''' # Category 3
item_redAppleID = float(2.1)
item_carrotID = float(2.2)
item_sliceOfWatermelonID = float(2.3)
item_watermelonID = float(2.4)
item_frenchBreadID = float(2.5)
item_frenchToastID = float(2.6)
item_loafOfWhiteBreadID = float(2.7)
item_wheatID = float(2.8)
item_sugarID = float(2.9)
item_chickenLegID = float(2.10)
item_chickenBreastID = float(2.11)
item_chickenWingID = float(2.12)
item_chickenHeadID = float(2.13)
item_boneID = float(2.14)
item_boneMealID = float(2.15)
item_oakWoodBowlID = float(2.16)
item_strawberryID = float(2.17)
item_cherryID = float(2.18)
item_rawChickenID = float(2.19)
item_cookedChickenID = float(2.20)
item_blueberryID = float(2.21)
item_raspberryID = float(2.22)
item_chocolateBarID = float(2.23)
item_blackberryID = float(2.24)
item_chickenEggID = float(2.25)
item_cocoaBeanID = float(2.26)
item_rawBaconID = float(2.27)
item_cookedBaconID = float(2.28)
item_rawPorkchopID = float(2.29)
item_cookedPorkchopID = float(2.30)
item_rawMuttonID = float(2.31)
item_cookedMuttonID = float(2.32)
item_rawSteakID = float(2.33)
item_cookedSteakID = float(2.34)
item_rawBeefID = float(2.35)
item_cookedBeefID = float(2.36)
item_lettuceID = float(2.37)
item_cabbageID = float(2.38)
item_bananaID = float(2.39)
item_walnutID = float(2.40)
item_pistachioID = float(2.41)
item_tomatoID = float(2.42)
item_ketchupID = float(2.43)
item_hamburgerID = float(2.44)
item_goatMilkID = float(2.45)
item_cheddarCheeseSliceID = float(2.46)
item_seaPickle_Count1ID = float(2.47)
item_seaPickle_Count2ID = float(2.48)
item_seaPickle_Count3ID = float(2.49)
item_seaPickle_Count4ID = float(2.50)
''' Building parts ''' # Category 4
item_redBrickID = float(3.1)
item_netherBrickID = float(3.2)
item_redNetherBrickID = float(3.3)
item_oakWoodStickID = float(3.4)
''' Potion brewing ''' # Category 5
item_emptyBottleID = float(4.1)
item_mundanePotionID = float(4.2)
item_awkwardPotionID = float(4.3)
item_fermentedSpiderEyeID = float(4.4)
item_blazePowderID = float(4.5)
item_magmaCreamID = float(4.6)
''' Exploring ''' # Category 6
item_compassID = float(5.1)
item_eyeOfEnderID = float(5.2)
''' Skins ''' # Category 7
item_chickenFeatherID = float(6.1)
item_cowLeatherID = float(6.2)
item_rabbitHydeID = float(6.3)
item_rabbitFootID = float(6.4)
''' Magical ''' # Category 8
item_NetherStarID = float(7.1)
item_enderPearlID = float(7.2)
''' Writing ''' # Category 9
item_bookAndQuillID = float(8.1)
item_paperID = float(8.2)
item_sandPaperID = float(8.3)
item_bookID = float(8.4)
item_enchantmentBook_silkTouch_ID = float(8.5)
item_enchantmentBook_featherFallingI_ID = float(8.6)
item_enchantmentBook_featherFallingII_ID = float(8.7)
item_enchantmentBook_featherFallingIII_ID = float(8.8)
item_enchantmentBook_featherFallingIV_ID = float(8.9)
item_enchantmentBook_featherFallingV_ID = float(8.10)
item_enchantmentBook_featherFallingVI_ID = float(8.11)
''' Display ''' # Category 10

''' Weapons ''' # Category 11
item_woodenBowID = float(10.1)
item_woodenCrossbowID = float(10.2)
item_oakWoodSwordID = float(10.3)
item_caveStoneSwordID = float(10.4)
item_cobbleStoneSwordID = floar(10.5)
''' Potions ''' # Category 12
''' tier 1 potion of invisibility makes you invisible to other players and mobs. The con of this is that if you are wearing armor, or holding an item, players can still see that '''
item_potionOfInvisibilityI_60S_ID = float(11.1) # Tier 1 potion of invisibility for 60 seconds
item_potionOfInvisibilityI_120S_ID = float(11.2) # Tier 1 potion of invisibility for 120 seconds
item_potionOfInvisibilityI_150S_ID = float(11.3) # Tier 1 potion of invisibility for 150 seconds
item_potionOfInvisibilityI_180S_ID = float(11.4) # Tier 1 potion of invisibility for 180 seconds
item_potionOfInvisibilityI_240S_ID = float(11.5) # Tier 1 potion of invisibility for 240 seconds
item_potionOfInvisibilityI_300S_ID = float(11.6) # Tier 1 potion of invisibility for 300 seconds
''' tier 2 potion of invisibility not only makes you invisible, but also the item you are holding, and your armor '''
item_potionOfInvisibilityII_60S_ID = float(11.7) # Tier 2 potion of invisibility for 60 seconds
item_potionOfInvisibilityII_120S_ID = float(11.8) # Tier 2 potion of invisibility for 120 seconds
item_potionOfInvisibilityII_150S_ID = float(11.9) # Tier 2 potion of invisibility for 150 seconds
item_potionOfInvisibilityII_180S_ID = float(11.10) # Tier 2 potion of invisibility for 180 seconds
item_potionOfInvisibilityII_240S_ID = float(11.11) # Tier 2 potion of invisibility for 240 seconds
item_potionOfInvisibilityII_300S_ID = float(11.12) # Tier 2 potion of invisibility for 300 seconds

#Mobs
''' Farm animals ''' # Category 1
mob_pigID = int(1)
mob_chickenID = int(2)
mob_cowID = int(3)
mob_mooshroomID = int(4)
mob_duckID = int(5)
mob_horseID = int(6)
mob_donkeyID = int(7)
mob_goatID = int(8)
mob_turkeyID = int(9)
mob_whiteSheepID = int(20) # This stays at the bottom of the category list until I add all the colors

''' Apocalypse ''' # Category 2
mob_normalZombieID = float(1.1)
mob_villagerZombieID = float(1.2)
mob_babyNormalZombieID = float(1.3)
mob_babyVillagerZombieID = float(1.4)
mob_giantNormalZombieID = float(1.5)
mob_giantVillagerZombieID = float(1.6)
mob_babyDrownedID = float(1.7)
mob_drownedID = float(1.8)
mob_babyChickenJockey = float(1.9)
''' Skeletons ''' # Category 3
mob_unarmedSkeletonID = float(2.1)
mob_armedSkeletonID = float(2.2)
mob_babyUnarmedSkeletonID = float(2.3)
mob_babyArmedSkeletonID = float(2.4)
mob_witherSkeletonID = float(2.5)
mob_babyWitherSkeletonID = float(2.6)
mob_skeletonHorseID = float(2.7)
mob_babySkeletonHorseID = float(2.8)
''' Magical ''' # Category 4
mob_witchID = float(3.1)
mob_babyWitchID = float(3.2)
''' In the end ''' # Category 5
mob_enderDragonID = float(4.1)
mob_endermanID = float(4.2)
''' Nether ''' # Category 6
mob_blazeID - float(5.1)
mob_babyBlazeID = float(5.2)
mob_magmaCubeSmallID = float(5.3)
mob_magmaCubeMediumID = float(5.4)
mob_magmaCubeLargeID = float(5.5)
mob_magmaCubeXLargeID = float(5.6)
mob_magmaCubeMassiveID = float(5.7)
mob_zombiePigmanID = float(5.8)
mob_babyZombiePigmanID = float(5.9)
mob_ghastID = float(5.10)
mob_babyGhastID = float(5.11)
mob_witherID = float(5.12)
''' Villagers ''' # Category 7
mob_testificateID = float(6.1)
mob_classicVillager1ID = float(6.2)
mob_classicVillager2ID = float(6.3)
mob_classicVillager3ID = float(6.4)
mob_classicVillager4ID = float(6.5)
mob_classicVillager5ID = float(6.6)
''' More birds ''' # Category 8
mob_blueParrotID = float(7.1)
mob_redParrotID = float(7.2)
mob_peacockID = float(7.3)
''' On the beach ''' # Category 9
mob_turtleID = float(8.1)
mob_babyTurtleID = float(8.2)
''' The pillager army ''' # Category 10
mob_vindicatorID = float(9.1)
mob_ravagerID = float(9.2)
mob_pillagerID = float(9.3)
mob_evokerID = float(9.4)
''' Bears ''' # Category 11
mob_brownBearID = float(10.1)
mob_pandaID = float(10.2)
mob_GrizzlyBearID = float(10.3)
mob_polarBearID = float(10.4)
''' Under the sea ''' # Category 12
mob_salmonID = float(11.1)
mob_guardianID = float(11.2)
mob_pufferFishID = float(11.3)
mob_goldFishID = float(11.4)
mob_dolphinID = float(11.5)
mob_babyDolphinID = float(11.6)
mob_starfishID = float(11.7)
''' Defenders of the village ''' # Category 13
mob_ironGolemID = float(12.1)
mob_babyIronGolemID = float(12.2)
mob_ironGolemiteID = float(12.3)
mob_steelGolemID = float(12.4)
mob_babySteelGolemID = float(12.5)
mob_steelGolemiteID = float(12.6)
mob_goldGolemID = float(12.7)
mob_babyGoldGolemID = float(12.8)
mob_goldGolemiteID = float(12.9)
mob_emeraldGolemID = float(12.10)
mob_babyEmeraldGolemID = float(12.11)
mob_emeraldGolemiteID = float(12.12)
mob_diamondGolemID = float(12.13)
mob_babyDiamondGolemID = float(12.14)
mob_diamonddGolemiteID = float(12.15)
''' Companions ''' # Category 14
mob_wolfID = float(13.1)
mob_babyWolfID = float(13.2)
mob_ocelotID = float(13.3)
mob_babyOcelotID = float(13.4)



''' ToDo '''
# make slabs and stairs of every block type
# Separate the files
# Get all 10 wood types of most items written in
""" End of script """
